accounts/urls.py
from django.urls import path

from .views import login_view, logout_view, signup_view

app_name = 'accounts'
urlpatterns = [
    path('login/',login_view,name='login'),
    path('logout/',logout_view,name='logout'),
    path('signup/',signup_view,name='signup')
]

quizzes/urls.py
from django.urls import path

from .views import display_questions, quiz_list, results

app_name = 'quizzes'
urlpatterns = [
    path('',quiz_list,name='quiz-list'),
    path('quiz/<int:pk>/',display_questions, name='display-question'),
    path('quiz/results/',results,name='results')
]

quizzy/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('',include('quizzes.urls',namespace='quizzes')),
    path('accounts/',include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
]

templates/_base.html
<!DOC>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">


    {% block css %}{% endblock css %}
    <title>Quizzy</title>
</head>
<body>

    <header class="p-2 bg-dark text-white">

        <div class="container">
            <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href={% url 'quizzes:quiz-list' %} class="nav-link px-2 text-white">Home</a></li>
                {% if request.user.is_authenticated %}
                    <li><a href={% url 'quizzes:results' %} class="nav-link px-2 text-white">Results</a></li>
                {% endif %}
            </ul>
    
            <div class="text-end">
                {% if not request.user.is_authenticated %}
                    <a href={% url 'accounts:login' %} class="btn btn-outline-light me-2">Login</a>
                    <a href={% url 'accounts:signup' %} class="btn btn-warning">Sign-up</a>
                {% else %} 
                    <a href={% url 'accounts:logout' %} class="btn btn-warning">Logout</a>
                {% endif %}
            </div>
            </div>
        </div>
        
    </header>
    <main>
        {% if request.user.is_authenticated %}
        <div>
            <p class="fs-1">Online:{{request.user.username}}</p>
        </div>
        <hr>
        {% endif %}
        {% block content %}
        {% endblock content %}
    </main>


    <!-- Bootstrap js -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    {% block js %}{% endblock js %}
</body>
</html>